name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Verificacion del codigo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      #Nuevo paso, autenticarme en docker hub
    - name: Proceso de login con Docker
      #Declaramos las variables de entorno, para que lea los secretos generados para autenticarnos con docker
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      #Estos comandos se ejecutaran dentro del servidor, permitiendo asi que nos logueemos para poder hacer el push de la imagen a docker hub
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
    - name: Construir la imagen de docker
      run: docker build -t luitzy/docker-graphql:0.0.2 . 

    - name: Subir imagen de docker
      run: docker push luitzy/docker-graphql:0.0.2 
